weapons:
  global:
    # Global overrides apply to any weapon that doesn't have a specific override below
    melee:
      can_stun: true            # Should a melee weapon stun if you get a headshot? (vanilla stun mechanic toggle)
      damage_modifier: 1.0      # Scale the amount of damage a melee weapon can do
      crit_chance: 0.1          # The chance that a melee weapon will do full damage (ie. the modifier is not applied)
      stun_on_crit: false       # Should a critical hit stun?
    
    ranged:
      can_stun: false           # Should a ranged weapon stun if you get a headshot? (vanilla stun mechanic toggle)
      damage_modifier: 1.0      # Scale the amount of damage a ranged weapon can do
      crit_chance: 0.1          # The chance that a melee weapon will do full damage (ie. the modifier is not applied)
      stun_on_crit: false       # Should a critical hit stun?
    
    limb_damage_modifiers:
      # The limb damage modifiers are used in place of the vanilla limb damage system
      # Note that due to floating point error and rounding, the values may be a point or two off in places
      head: 1.1
      body: 1.0
      spine: 0.6
      arms: 0.3
      legs: 0.3
  
  overrides:
    # For our overrides, we mainly deal with melee weapons. The logic applied is that they fall under two categories - bladed and blunt.
    # Blunt weapons should be able to stun a zombie with a headshot but shouldn't do much damage, where bladed do lots of damage but won't stun
    # Think of it like concussing a zombie vs slicing their arm off. Certain weapons, such as the crowbar, are an exception as they are both
    # somewhat blunt but also have sharp parts which could embed themselves
    
    0: # Fists
      can_stun: false
      damage: 2
      crit_damage: 5
      crit_chance: 0.1
      stun_on_crit: true
      
    16: # Camp Axe
      can_stun: false
      damage: 25
      crit_damage: 45
      crit_chance: 0.05
      stun_on_crit: false
      
    76: # Blowtorch
      can_stun: false
      damage: 3
      crit_damage: 5
      crit_chance: 0.0
      stun_on_crit: false
      
    104: # Fire Axe
      can_stun: false
      damage: 35
      crit_damage: 70
      crit_chance: 0.1
      stun_on_crit: false
      
    105: # Baseball Bat
      can_stun: true
      damage: 18
      crit_damage: 18
      crit_chance: 0.0
      stun_on_crit: false
      
    106: # Hockey Stick
      can_stun: true
      damage: 13
      crit_damage: 13
      crit_chance: 0.0
      stun_on_crit: false
      
    120: # Kitchen Knife
      can_stun: false
      damage: 10
      crit_damage: 10
      crit_chance: 0.0
      stun_on_crit: false
      
    121: # Military Knife
      can_stun: false
      damage: 15
      crit_damage: 15
      crit_chance: 0.0
      stun_on_crit: false
      
    135: # Golf Club
      can_stun: true
      damage: 20
      crit_damage: 20
      crit_chance: 0.0
      stun_on_crit: false
      
    136: # Sledgehammer
      can_stun: true
      damage: 50
      crit_damage: 50
      crit_chance: 0.0
      stun_on_crit: false
      
    137: # Butcher Knife
      can_stun: true
      damage: 12
      crit_damage: 12
      crit_chance: 0.0
      stun_on_crit: false
      
    138: # Hammer
      can_stun: true
      damage: 10
      crit_damage: 25
      crit_chance: 0.1
      stun_on_crit: false
    
    139: # Pocket Knife
      can_stun: true
      damage: 10
      crit_damage: 15
      crit_chance: 0.0
      stun_on_crit: false
      
    140: # Butterfly Knife
      can_stun: true
      damage: 10
      crit_damage: 40
      crit_chance: 0.0
      stun_on_crit: false
      
    141: # Saw
      can_stun: false
      damage: 20
      crit_damage: 25
      crit_chance: 0.0
      stun_on_crit: false
      
    142: # Rake
      can_stun: true
      damage: 12
      crit_damage: 15
      crit_chance: 0.0
      stun_on_crit: false
    
    276: # Flash Light
      can_stun: false
      damage: 5
      crit_damage: 10
      crit_chance: 0.0
      stun_on_crit: false
      
    487: # Makeshift Bat
      can_stun: true
      damage: 22
      crit_damage: 40
      crit_chance: 0.2
      stun_on_crit: false
    
    490: # Chainsaw
      can_stun: false
      damage: 25
      crit_damage: 25
      crit_chance: 0.0
      stun_on_crit: false
      
    1023: # Baton
      can_stun: true
      damage: 10
      crit_damage: 15
      crit_chance: 0.0
      stun_on_crit: false
      
    1030: # Frying Pan
      can_stun: true
      damage: 15
      crit_damage: 15
      crit_chance: 0.0
      stun_on_crit: false
      
    1031: # Shovel
      can_stun: true
      damage: 15
      crit_damage: 15
      crit_chance: 0.0
      stun_on_crit: false
      
    1032: # Crowbar
      can_stun: false
      damage: 15
      crit_damage: 25
      crit_chance: 0.1
      stun_on_crit: false
      
    1033: # Paddle
      can_stun: true
      damage: 15
      crit_damage: 15
      crit_chance: 0.0
      stun_on_crit: false
      
    1034: # Pitchfork
      can_stun: false
      damage: 15
      crit_damage: 15
      crit_chance: 0.05
      stun_on_crit: false
      
    1035: # Machete
      can_stun: true
      damage: 30
      crit_damage: 50
      crit_chance: 0.2
      stun_on_crit: false
      
    1036: # Katana
      can_stun: false
      damage: 30
      crit_damage: 60
      crit_chance: 0.3
      stun_on_crit: false
      
    1174: # Sycthe
      can_stun: false
      damage: 35
      crit_damage: 60
      crit_chance: 0.2
      stun_on_crit: false
      
    1198: # Pickaxe
      can_stun: false
      damage: 20
      crit_damage: 80
      crit_chance: 0.1
      stun_on_crit: false
      
    1390: # Pool Cue
      can_stun: true
      damage: 10
      crit_damage: 15
      crit_chance: 0.0
      stun_on_crit: false
      
    1475: # Jackhammer
      can_stun: false
      damage: 20
      crit_damage: 30
      crit_chance: 0.1
      stun_on_crit: false
      
    1503: # Zweihander
      can_stun: false
      damage: 60
      crit_damage: 100
      crit_chance: 0.1
      stun_on_crit: false